name: RUN

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  

    - name: Run install.sh
      run: |
        chmod +x install.sh
        ./install.sh

    - name: Run main.py and store output
      run: |
        source env/bin/activate
        python main.py > output.txt

    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output-file
        path: output.txt

    - name: Download output file
      uses: actions/download-artifact@v2
      with:
        name: output-file
        path: .

    - name: Send output file to Discord
      run: |
        curl -X POST "https://discord.com/api/webhooks/1222208487283626055/wNRotWI9_uyXvhHZ-UQZxQWnHzajZzjAkKF6jQTgwFUNSrpHfHTsejFXYV-c9QXL64i4" \
        -F "file=@output.txt"
