name: RUN

on:
  push:
    tags:
      - '*'

jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  
        
    - name: Run install.sh
      run: |
        chmod +x install.sh
        ./install.sh

    - name: Run main.py and store output
      run: |
        source env/bin/activate
        python main.py > output.txt

    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output-file
        path: output.txt
